const propiedades = {
    data:[
    {
        propiedadNombre: 'Departamento en Belgrano',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '1',
        precio: '80000',
        barrio: 'Belgrano',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Belgrano',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '1',
        precio: '110000',
        barrio: 'Belgrano',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Departamento en Belgrano',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '1',
        precio: '200',
        barrio: 'Belgrano',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Belgrano',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '2',
        precio: '90000',
        barrio: 'Belgrano',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Belgrano',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '2',
        precio: '150000',
        barrio: 'Belgrano',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Departamento en Belgrano',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '2',
        precio: '300',
        barrio: 'Belgrano',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Belgrano',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '3',
        precio: '400',
        barrio: 'Belgrano',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Belgrano',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '3',
        precio: '230000',
        barrio: 'Belgrano',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Departamento en Palermo',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '3',
        precio: '120000',
        barrio: 'Palermo',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Palermo',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '3',
        precio: '220000',
        barrio: 'Palermo',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Departamento en Palermo',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '3',
        precio: '400',
        barrio: 'Palermo',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Palermo',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '4',
        precio: '150000',
        barrio: 'Palermo',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Palermo',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '4',
        precio: '500',
        barrio: 'Palermo',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Palermo',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '2',
        precio: '100000',
        barrio: 'Palermo',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Palermo',
        opcion: 'Alquiler',
        tipo: 'Casa',
        ambientes: '2',
        precio: '300',
        barrio: 'Palermo',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Villa Urquiza',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '3',
        precio: '120000',
        barrio: 'Villa Urquiza',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Villa Urquiza',
        opcion: 'Alquiler',
        tipo: 'Casa',
        ambientes: '3',
        precio: '400',
        barrio: 'Villa Urquiza',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Villa Urquiza',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '4',
        precio: '160000',
        barrio: 'Villa Urquiza',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Villa Urquiza',
        opcion: 'Alquiler',
        tipo: 'Casa',
        ambientes: '4',
        precio: '500',
        barrio: 'Villa Urquiza',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Departamento en Recoleta',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '3',
        precio: '150000',
        barrio: 'Recoleta',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Recoleta',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '3',
        precio: '600',
        barrio: 'Recoleta',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Recoleta',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '4',
        precio: '260000',
        barrio: 'Recoleta',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Recoleta',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '4',
        precio: '800',
        barrio: 'Recoleta',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Caballito',
        opcion: 'Venta',
        tipo: 'Departamento',
        ambientes: '2',
        precio: '130000',
        barrio: 'Caballito',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Departamento en Caballito',
        opcion: 'Alquiler',
        tipo: 'Departamento',
        ambientes: '2',
        precio: '300',
        barrio: 'Caballito',
        image: 'img/arquitectura-moderna-apartamentos.jpg',
    },
    {
        propiedadNombre: 'Casa en Caballito',
        opcion: 'Venta',
        tipo: 'Casa',
        ambientes: '4',
        precio: '200000',
        barrio: 'Caballito',
        image: 'img/casa.jpg',
    },
    {
        propiedadNombre: 'Casa en Caballito',
        opcion: 'Alquiler',
        tipo: 'Casa',
        ambientes: '4',
        precio: '700',
        barrio: 'Caballito',
        image: 'img/casa.jpg',
    },
]
}
